### ISSUE TITLE
Ошибка при фильтрации модулей по зависимостям

### ISSUE THREAD

**Issue by tenorok** [tenorok/bemaker#2]
Если в папках с блоками отсутствует блок, указанный где-то в зависимостях, то выводится неочевидная JS-ошибка.

Метод [`_filter`](https://github.com/tenorok/bemaker/blob/v0.1.3/modules/Depend.js#L109) сначала вызывается со значением `button` в параметре `name`, а затем рекурсивно из цикла запускается со значением `i-control` в параметре `name`. Так получается, что на этот момент блок `i-control` ещё не был прочитан и метод [`get`](https://github.com/tenorok/bemaker/blob/v0.1.3/modules/Pool.js#L165) возвращает `null`.

Вот текст ошибки:

``` bash
Possibly unhandled TypeError: Cannot read property 'name' of null
    at Object.Depend._filter (/Users/tenorok/projects/multf/node_modules/grunt-bemaker/node_modules/bemaker/modules/Depend.js:110:51)
    at Object.<anonymous> (/Users/tenorok/projects/multf/node_modules/grunt-bemaker/node_modules/bemaker/modules/Depend.js:112:18)
```

Нужно сообщать в явном виде, что не был найден блок, указанный в зависимостях. И возможно, не останавливать при этом сборку, потому что это не критично.

**Comment by tenorok** [comment]
Исправлена ошибка, возникающая при получении имени несуществующего модуля в методе `Depend#filter`.

Инициируется событие `unexist` обнаружения несуществующего модуля.

Событие `circle` переименовано в `loop`.

https://github.com/tenorok/bemaker/commit/855e85525d93510715c54c7b90d96f8ea7658192
